1. What is a Python library? Why do we use Python libraries?
- answer: Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language.Using Python libraries makes it convenient for the us as we don't have to write the same code multiple times for different programs.



2. What is the difference between Numpy array and List?

|Numpy Array|	Python List|
|-|-|
|It is the core Library of python which is used for scientific computing.	|The core library of python provides list.|
|It can contain similar datatypes.	|It Contains different types of datatypes.|
|We need to Numpy Library to access Numpy Arrays.|It is built-in function of python.|
|It is Homogeneous.|	It is both homogeneous and heterogeneous.|
|In this Element wise operation is possible.|	Element wise operation is not possible on the list.|
|By using numpy.array() we can create N-Dimensional array.|	It is by default 1-dimensional.In some cases, we can create an N-Dimensional list. But it is a long process.|
|It requires smaller memory consumption as compared to Python List.	|It requires more memory as compared to Numpy Array.|
|In this each item is stored in a sequential manner.|	It stores item in random location of  the memory.|
|It is faster as compared to list.	|It is slow as compared to NumPy Array.|
|It also have some optimism function .|	It does not have some optimism function .|

In [11]:
'''3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

import numpy as np

arr = np.array([ [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]])
print(arr.shape,'\n',
      arr.size, '\n',
      arr.ndim)

(3, 4) 
 12 
 2


In [12]:
'''4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr[0]

array([1, 2, 3, 4])

In [14]:
'''5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr[0, 3]

4

In [20]:
'''6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    if (i%2  != 0) & (j%2 !=0):
      print(arr[i,j])



6
8


In [24]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
mt = np.random.random(size=[3,3])
mt

array([[0.47166131, 0.39798078, 0.74726149],
       [0.17653727, 0.28648339, 0.25018536],
       [0.99139543, 0.72666176, 0.78118414]])

8. Describe the difference between np.random.rand and np.random.randn?
randn generates samples from the normal distribution, while numpy. random. rand from a uniform distribution (in the range [0,1))

In [28]:
'''9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

arr9 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
np. expand_dims(arr9, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [29]:
'''10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [42]:
'''
11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
1. Index wise multiplication
2. Matix multiplication
3. Add both the matix
4. Subtact matix B from A
5. Divde Matix B by A
'''
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

#1
print("1: \n", np.multiply(A, B))

#2
print("2: \n", np.dot(A,B.T))

#  3
print("3: \n", np.add(A,B))

#4
print("4: \n", A-B)

#5
print("5: \n", B/A)

1: 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
2: 
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
3: 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
4: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
5: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?<br>
answer: ndarray.byteswap(inplace=False): Swap the bytes of the array elements

13. What is the significance of the np.linalg.inv function?<br>
answer: NumPy linalg. inv() function in Python is used to compute the (multiplicative) inverse of a matrix.

14. What does the np.reshape function do, and how is it used?<br>
answer: You can think of reshaping as first raveling the array (using the given index order), then inserting the elements from the raveled array into the new array

15. What is broadcasting in Numpy?<br>
answer: broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements